<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ search by suburb</name>
   <tag></tag>
   <elementGuidId>724f1de1-f11a-4ec6-aa68-a1fb09316f05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='block-content']/article/section/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.page-wrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-wrapper</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
  
    Search by suburb, postcode or current locationStart typing to see suggestionsFilter by centre typeAllService CentresMobile Service CentresService NSW locationsList viewMap viewService NSW locationsThere are Service NSW locations all across the state. To find one near you, search your suburb above or zoom in on the map.KeyService CentreCurrent locationUpcoming locationMapTerrainSatelliteLabelsMap DataMap data ©2021 GoogleTerms of UseReport a map errorMap data ©2021 GoogleMap DataMap data ©2021 Google
  
</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-content&quot;)/article[@class=&quot;landing-page&quot;]/section[@class=&quot;landing-page__section&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;region&quot;]/div[@class=&quot;block&quot;]/div[@class=&quot;page-wrapper&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-content']/article/section/div/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='face masks'])[1]/following::div[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Note:'])[1]/following::div[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div</value>
   </webElementXpaths>
</WebElementEntity>
